#!/usr/bin/env python3
"""Scan every *Response.java and *Request.java under src/, extract JSON keys
from record components (via @JsonProperty), and dump them as markdown tables
for cross-DTO consistency review.

For Requests we also surface the bean-validation annotations on each component
(@NotNull, @NotBlank, @Valid, @Size, ...) since that's where request DTOs
tend to diverge.
"""
import re
import sys
from pathlib import Path

ROOT = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else Path(r"C:\Users\DavideTonin\IdeaProjects\doc-exchange-service")
SRC = ROOT / "src"
CHECKLISTS = ROOT / "docs" / "checklists"

RECORD_RE = re.compile(r"public\s+record\s+(\w+)\s*\((.*?)\)\s*(?:implements[^{]+)?\{", re.S)
INTERFACE_RE = re.compile(r"public\s+sealed\s+interface\s+(\w+)\b.*?permits\s+([\w,\s]+)", re.S)
JSONPROP_RE = re.compile(r'@JsonProperty\(\s*"([^"]+)"\s*\)')
# Bean-validation / binding annotations we care about for requests.
VALIDATION_ANNOS = re.compile(
    r"@(NotNull|NotBlank|NotEmpty|Valid|Size|Email|Positive|PositiveOrZero|"
    r"Negative|Min|Max|Pattern|Past|Future|PastOrPresent|FutureOrPresent|"
    r"AssertTrue|AssertFalse|Digits|DecimalMin|DecimalMax|JsonProperty)\b"
)

def split_components(body: str):
    """Split a record component list on top-level commas."""
    parts, depth, current = [], 0, ""
    for ch in body:
        if ch in "(<{":
            depth += 1
        elif ch in ")>}":
            depth -= 1
        if ch == "," and depth == 0:
            parts.append(current)
            current = ""
        else:
            current += ch
    if current.strip():
        parts.append(current)
    return parts

def strip_annotations(s: str):
    result, i, n = [], 0, len(s)
    while i < n:
        if s[i] == "@":
            j = i + 1
            while j < n and (s[j].isalnum() or s[j] == "_" or s[j] == "."):
                j += 1
            if j < n and s[j] == "(":
                depth, j = 1, j + 1
                while j < n and depth > 0:
                    if s[j] == "(":
                        depth += 1
                    elif s[j] == ")":
                        depth -= 1
                    j += 1
            i = j
        else:
            result.append(s[i])
            i += 1
    return "".join(result)

def strip_line_comments(s: str):
    return "\n".join(re.sub(r"//.*", "", ln) for ln in s.splitlines())

def parse_component(part: str):
    part = strip_line_comments(part).strip()
    if not part:
        return None
    json_key_match = JSONPROP_RE.search(part)
    json_key = json_key_match.group(1) if json_key_match else None
    validations = [m.group(1) for m in VALIDATION_ANNOS.finditer(part) if m.group(1) != "JsonProperty"]
    stripped = strip_annotations(part).strip()
    tokens = stripped.split()
    if len(tokens) < 2:
        return None
    field_name = tokens[-1]
    field_type = " ".join(tokens[:-1])
    if json_key is None:
        json_key = field_name
    return json_key, field_name, field_type, validations

def scan(suffix):
    files = sorted(SRC.rglob(f"*{suffix}.java"))
    interfaces, summary_rows = [], []
    full_rows_by_class = {}
    for f in files:
        text = f.read_text(encoding="utf-8")
        rel = f.relative_to(ROOT).as_posix()
        rec_match = RECORD_RE.search(text)
        if rec_match:
            class_name, body = rec_match.group(1), rec_match.group(2)
            rows = [r for r in (parse_component(p) for p in split_components(body)) if r]
            summary_rows.append((class_name, rel))
            full_rows_by_class[class_name] = rows
            continue
        iface_match = INTERFACE_RE.search(text)
        if iface_match:
            class_name, permits = iface_match.group(1), iface_match.group(2)
            interfaces.append((class_name, rel, [p.strip() for p in permits.split(",")]))
            continue
        summary_rows.append((f.stem, rel))
        full_rows_by_class[f.stem] = None
    return files, interfaces, summary_rows, full_rows_by_class

def write_per_class(kind, suffix, files, interfaces, summary_rows, full_rows_by_class, show_validation):
    lines = [f"# JSON {kind} Field Audit\n"]
    lines.append(
        f"Auto-generated by `development/extract-dto-fields.py`. Every JSON key on each "
        f"`*{suffix}` record, in declaration order.\n"
    )
    lines.append(f"\nScanned **{len(files)}** `*{suffix}` files: **{len(full_rows_by_class)}** records, "
                 f"**{len(interfaces)}** sealed interfaces.\n")
    lines.append("\n## Index\n")
    lines.append("| Class | File |")
    lines.append("|---|---|")
    for class_name, rel in summary_rows:
        lines.append(f"| [{class_name}](#{class_name.lower()}) | `{rel}` |")
    for class_name, rel, permits in interfaces:
        lines.append(f"| {class_name} *(interface → {', '.join(permits)})* | `{rel}` |")

    lines.append("\n## Fields per class\n")
    for class_name, rel in summary_rows:
        lines.append(f"\n### {class_name}\n")
        lines.append(f"`{rel}`\n")
        rows = full_rows_by_class.get(class_name)
        if rows is None:
            lines.append("_Could not parse record components — check manually._\n")
            continue
        if not rows:
            lines.append("_No components (marker record)._\n")
            continue
        if show_validation:
            lines.append("| # | JSON Key | Java Field | Type | Validation |")
            lines.append("|---|---|---|---|---|")
            for idx, (json_key, field_name, field_type, validations) in enumerate(rows, start=1):
                v = ", ".join(f"`@{a}`" for a in validations) if validations else "—"
                lines.append(f"| {idx} | `{json_key}` | `{field_name}` | `{field_type}` | {v} |")
        else:
            lines.append("| # | JSON Key | Java Field | Type |")
            lines.append("|---|---|---|---|")
            for idx, (json_key, field_name, field_type, _v) in enumerate(rows, start=1):
                lines.append(f"| {idx} | `{json_key}` | `{field_name}` | `{field_type}` |")

    if interfaces:
        lines.append("\n## Sealed interfaces (no own fields)\n")
        for class_name, rel, permits in interfaces:
            lines.append(f"\n### {class_name}\n")
            lines.append(f"`{rel}` — permits: {', '.join(f'`{p}`' for p in permits)}\n")

    out = CHECKLISTS / f"{suffix.lower()}_json_fields.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out}")

def write_matrix(kind, suffix, full_rows_by_class):
    rows_by_class = {c: r for c, r in full_rows_by_class.items() if r}
    class_names = sorted(rows_by_class.keys())
    key_to_class_type = {}
    for class_name, rows in rows_by_class.items():
        for json_key, field_name, field_type, _v in rows:
            key_to_class_type.setdefault(json_key, {})[class_name] = field_type
    all_keys = sorted(key_to_class_type.keys())

    lines = [f"# JSON {kind} Field Matrix\n"]
    lines.append(
        f"Auto-generated by `development/extract-dto-fields.py`. Columns = `*{suffix}` classes, "
        f"rows = every distinct JSON key. Cell = the Java type under that key; blank = absent. "
        f"Scan a row to spot naming/type drift for the same concept.\n"
    )
    lines.append(f"\n{len(class_names)} classes x {len(all_keys)} distinct keys.\n")
    lines.append("| JSON Key | " + " | ".join(class_names) + " |")
    lines.append("|---|" + "|".join(["---"] * len(class_names)) + "|")
    for key in all_keys:
        row = [f"`{key}`"]
        per_class = key_to_class_type[key]
        for class_name in class_names:
            ft = per_class.get(class_name, "")
            row.append(f"`{ft}`" if ft else "")
        lines.append("| " + " | ".join(row) + " |")

    out = CHECKLISTS / f"{suffix.lower()}_json_field_matrix.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out} ({len(class_names)} classes x {len(all_keys)} keys)")

def main():
    CHECKLISTS.mkdir(parents=True, exist_ok=True)
    for suffix, kind, show_validation in [("Response", "Response", False), ("Request", "Request", True)]:
        files, interfaces, summary_rows, full_rows_by_class = scan(suffix)
        write_per_class(kind, suffix, files, interfaces, summary_rows, full_rows_by_class, show_validation)
        write_matrix(kind, suffix, full_rows_by_class)

if __name__ == "__main__":
    main()
